# Telegram credentials
API_ID = "28126323"
API_HASH = "54320bbb3dacbe10b65700d419acddec"
PHONE_NUMBER = "+46762497321"
BOT_USERNAME = "walletx_solana_bot"

# Supabase credentials
SUPABASE_URL = "https://lzwsybrstgqobdotjjmy.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6d3N5YnJzdGdxb2Jkb3Rqam15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwNDE5OTksImV4cCI6MjA1MzYxNzk5OX0.BX4ofo56SnnDVifdyusHJI7dekxuVwIDfO6nmNQuTvQ" 